samplesheet:     "docs/samplesheet.csv"
fast5_dir:       "/nfs/research/zi/zi/projects/tb/mada-mumbai-sputum/nanopore/fast5"
basecall_config: "dna_r9.4.1_450bps_sup_prom.cfg"
containers:
  guppy-gpu: "docker://quay.io/mbhall88/guppy-gpu:5.0.16"
  guppy-cpu: "docker://quay.io/mbhall88/guppy-cpu:5.0.16"
  base:      "docker://bash:5.1"